apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: backend-virtual-service
spec:
 hosts:
 - nodejs-store-backend
 gateways:
 - mesh
 http:
 - route:
   - destination:
       host: nodejs-store-backend.default.svc.cluster.local   
       port:
         number: 8080